### ISSUE TITLE
[question] conda or virtualenv ?

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-ui#156]
Hello,

Current radis-ui suggests to use Virtualenv to manage the Python backend. Is there any reason you chose this over Conda ?

Coming from the scientific Python background, usually conda is the default, but that's mostly because we don't know of virtualenv ;) 
[This article](https://deeplearning.lipingyang.org/2018/12/23/anaconda-vs-miniconda-vs-virtualenv/) suggests to "use virtualenv  when you have sudo access" but is not very explicit to why it's better ?

**Comment by suzil** [comment]
There's no code in the repo that is specific for virtualenv or conda. I put the installation with virtualenv since that's the simplest and [builtin to Python since Python 3.3](https://docs.python.org/3/library/venv.html).

Either one can be used though. A lot of repos won't even indicate how to manage the virtual environment as it's considered more of a user preference.

**Comment by erwanp** [comment]
Clear for me, closing !
