### ISSUE TITLE
No molecule in selection box

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-ui#188]
![image](https://user-images.githubusercontent.com/16088743/104199110-53b8a680-5427-11eb-9196-174f8248e052.png)

May be because of the last merge #183. 

And a different suggestion/bug than #185

**Comment by suzil** [comment]
This is due to the request blocking (https://github.com/suzil/radis-ui/issues/177) because the molecules are populated there by calling `/molecules` from the backend. Getting to be a pretty annoying issue so I might try to dedicate some time to fixing it...

![Screen Shot 2021-01-11 at 10 39 00 AM](https://user-images.githubusercontent.com/13723264/104211060-3967d400-53f9-11eb-9de9-b2688afee3c0.png)

**Comment by erwanp** [comment]
Fixed too here!
